<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_An41MB8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.an41MB8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.2T.KYtP.App\\Controller\\Admin\\BlogController::index()', 'getBlogControllerindex2Service', true],
            'App\\Controller\\Admin\\BlogController::new' => ['privates', '.service_locator.8m8R3s_.App\\Controller\\Admin\\BlogController::new()', 'getBlogControllernewService', true],
            'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator.7j.FZ9c.App\\Controller\\Admin\\BlogController::show()', 'getBlogControllershowService', true],
            'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.q4lYT8b.App\\Controller\\Admin\\BlogController::edit()', 'getBlogControllereditService', true],
            'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.q4lYT8b.App\\Controller\\Admin\\BlogController::delete()', 'getBlogControllerdeleteService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.0xtdKU7.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\BlogController::postShow' => ['privates', '.service_locator.7j.FZ9c.App\\Controller\\BlogController::postShow()', 'getBlogControllerpostShowService', true],
            'App\\Controller\\BlogController::commentNew' => ['privates', '.service_locator.tFX39bs.App\\Controller\\BlogController::commentNew()', 'getBlogControllercommentNewService', true],
            'App\\Controller\\BlogController::commentForm' => ['privates', '.service_locator.7j.FZ9c.App\\Controller\\BlogController::commentForm()', 'getBlogControllercommentFormService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.siBFJLB.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.8m8R3s_.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.zvHAzmR.App\\Controller\\UserController::changePassword()', 'getUserControllerchangePasswordService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.2T.KYtP.App\\Controller\\Admin\\BlogController::index()', 'getBlogControllerindex2Service', true],
            'App\\Controller\\Admin\\BlogController:new' => ['privates', '.service_locator.8m8R3s_.App\\Controller\\Admin\\BlogController::new()', 'getBlogControllernewService', true],
            'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator.7j.FZ9c.App\\Controller\\Admin\\BlogController::show()', 'getBlogControllershowService', true],
            'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.q4lYT8b.App\\Controller\\Admin\\BlogController::edit()', 'getBlogControllereditService', true],
            'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.q4lYT8b.App\\Controller\\Admin\\BlogController::delete()', 'getBlogControllerdeleteService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.0xtdKU7.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\BlogController:postShow' => ['privates', '.service_locator.7j.FZ9c.App\\Controller\\BlogController::postShow()', 'getBlogControllerpostShowService', true],
            'App\\Controller\\BlogController:commentNew' => ['privates', '.service_locator.tFX39bs.App\\Controller\\BlogController::commentNew()', 'getBlogControllercommentNewService', true],
            'App\\Controller\\BlogController:commentForm' => ['privates', '.service_locator.7j.FZ9c.App\\Controller\\BlogController::commentForm()', 'getBlogControllercommentFormService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.siBFJLB.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.8m8R3s_.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.zvHAzmR.App\\Controller\\UserController::changePassword()', 'getUserControllerchangePasswordService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\BlogController::index' => '?',
            'App\\Controller\\Admin\\BlogController::new' => '?',
            'App\\Controller\\Admin\\BlogController::show' => '?',
            'App\\Controller\\Admin\\BlogController::edit' => '?',
            'App\\Controller\\Admin\\BlogController::delete' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::postShow' => '?',
            'App\\Controller\\BlogController::commentNew' => '?',
            'App\\Controller\\BlogController::commentForm' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::changePassword' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\BlogController:index' => '?',
            'App\\Controller\\Admin\\BlogController:new' => '?',
            'App\\Controller\\Admin\\BlogController:show' => '?',
            'App\\Controller\\Admin\\BlogController:edit' => '?',
            'App\\Controller\\Admin\\BlogController:delete' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:postShow' => '?',
            'App\\Controller\\BlogController:commentNew' => '?',
            'App\\Controller\\BlogController:commentForm' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:changePassword' => '?',
        ]);

        if (isset($container->privates['.service_locator.an41MB8'])) {
            return $container->privates['.service_locator.an41MB8'];
        }

        return $container->privates['.service_locator.an41MB8'] = $instance;
    }
}
