<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_IconifyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux_icons.iconify' shared service.
     *
     * @return \Symfony\UX\Icons\Iconify
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-icons'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Iconify.php';

        return $container->privates['.ux_icons.iconify'] = new \Symfony\UX\Icons\Iconify(($container->privates['.ux_icons.cache'] ?? self::get_UxIcons_CacheService($container)), 'https://api.iconify.design', ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
