<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7j_FZ9cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7j.FZ9c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7j.FZ9c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.7j.FZ9c.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.7j.FZ9c": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
