<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_CacheIconRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux_icons.cache_icon_registry' shared service.
     *
     * @return \Symfony\UX\Icons\Registry\CacheIconRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-icons'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'IconRegistryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-icons'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Registry'.\DIRECTORY_SEPARATOR.'CacheIconRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-icons'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Registry'.\DIRECTORY_SEPARATOR.'ChainIconRegistry.php';

        return $container->privates['.ux_icons.cache_icon_registry'] = new \Symfony\UX\Icons\Registry\CacheIconRegistry(new \Symfony\UX\Icons\Registry\ChainIconRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.ux_icons.local_svg_icon_registry'] ??= new \Symfony\UX\Icons\Registry\LocalSvgIconRegistry((\dirname(__DIR__, 4).'/assets/icons'), []));
            yield 1 => ($container->privates['.ux_icons.iconify_on_demand_registry'] ?? $container->load('get_UxIcons_IconifyOnDemandRegistryService'));
        }, 2)), ($container->privates['.ux_icons.cache'] ?? self::get_UxIcons_CacheService($container)));
    }
}
