<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\AppExtension' shared autowired service.
     *
     * @return \App\Twig\AppExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'AppExtension.php';

        return $container->privates['App\\Twig\\AppExtension'] = new \App\Twig\AppExtension($container->parameters['kernel.enabled_locales'], 'en');
    }
}
