<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7j.FZ9c.App\Controller\Admin\BlogController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7j.FZ9c.App\\Controller\\Admin\\BlogController::show()'] = ($container->privates['.service_locator.7j.FZ9c'] ?? $container->load('get_ServiceLocator_7j_FZ9cService'))->withContext('App\\Controller\\Admin\\BlogController::show()', $container);
    }
}
