<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllercommentNewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tFX39bs.App\Controller\BlogController::commentNew()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.tFX39bs.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.tFX39bs": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
            'post' => ['privates', '.errored..service_locator.tFX39bs.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.tFX39bs": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.'],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'post' => 'App\\Entity\\Post',
            'eventDispatcher' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\BlogController::commentNew()', $container);

        if (isset($container->privates['.service_locator.tFX39bs.App\\Controller\\BlogController::commentNew()'])) {
            return $container->privates['.service_locator.tFX39bs.App\\Controller\\BlogController::commentNew()'];
        }

        return $container->privates['.service_locator.tFX39bs.App\\Controller\\BlogController::commentNew()'] = $instance;
    }
}
