<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0xtdKU7.App\Controller\BlogController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0xtdKU7.App\\Controller\\BlogController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'posts' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'tags' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'posts' => 'App\\Repository\\PostRepository',
            'tags' => 'App\\Repository\\TagRepository',
        ]))->withContext('App\\Controller\\BlogController::index()', $container);
    }
}
