<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8m8R3s_.App\Controller\Admin\BlogController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8m8R3s_.App\\Controller\\Admin\\BlogController::new()'] = ($container->privates['.service_locator.8m8R3s_'] ?? $container->load('get_ServiceLocator_8m8R3sService'))->withContext('App\\Controller\\Admin\\BlogController::new()', $container);
    }
}
