<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogSearchComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\BlogSearchComponent' autowired service.
     *
     * @return \App\Twig\Components\BlogSearchComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'BlogSearchComponent.php';

        $container->factories['App\\Twig\\Components\\BlogSearchComponent'] = function ($container) {
            return new \App\Twig\Components\BlogSearchComponent(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')));
        };

        return $container->factories['App\\Twig\\Components\\BlogSearchComponent']($container);
    }
}
