<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q4lYT8b.App\Controller\Admin\BlogController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q4lYT8b.App\\Controller\\Admin\\BlogController::delete()'] = ($container->privates['.service_locator.q4lYT8b'] ?? $container->load('get_ServiceLocator_Q4lYT8bService'))->withContext('App\\Controller\\Admin\\BlogController::delete()', $container);
    }
}
