<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListUsersCommand_CommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ListUsersCommand.command' shared service.
     *
     * @return \Symfony\Component\Console\Command\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ListUsersCommand.php';

        $container->privates['App\\Command\\ListUsersCommand.command'] = $instance = new \Symfony\Component\Console\Command\Command();

        $instance->setCode(new \App\Command\ListUsersCommand(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), 'anonymous@example.com', ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'))));
        $instance->setName('app:list-users');
        $instance->setAliases(['app:users']);
        $instance->setHelp('The <info>%command.name%</info> command lists all the users registered in the application:'."\n".''."\n".'  <info>php %command.full_name%</info>'."\n".''."\n".'By default the command only displays the 50 most recent users. Set the number of'."\n".'results to display with the <comment>--max-results</comment> option:'."\n".''."\n".'  <info>php %command.full_name%</info> <comment>--max-results=2000</comment>'."\n".''."\n".'In addition to displaying the user list, you can also send this information to'."\n".'the email address specified in the <comment>--send-to</comment> option:'."\n".''."\n".'  <info>php %command.full_name%</info> <comment>--send-to=fabien@symfony.com</comment>');
        $instance->setDescription('Lists all the existing users');

        return $instance;
    }
}
