<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPost3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tFX39bs.App\Entity\Post' shared service.
     *
     * @return \App\Entity\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tFX39bs": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
