<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeInfo_Resolver_ReflectionTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'type_info.resolver.reflection_type' shared service.
     *
     * @return \Symfony\Component\TypeInfo\TypeResolver\ReflectionTypeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'type-info'.\DIRECTORY_SEPARATOR.'TypeResolver'.\DIRECTORY_SEPARATOR.'TypeResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'type-info'.\DIRECTORY_SEPARATOR.'TypeResolver'.\DIRECTORY_SEPARATOR.'ReflectionTypeResolver.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'type-info'.\DIRECTORY_SEPARATOR.'TypeContext'.\DIRECTORY_SEPARATOR.'TypeContextFactory.php';

        return $container->privates['type_info.resolver.reflection_type'] = new \Symfony\Component\TypeInfo\TypeResolver\ReflectionTypeResolver(($container->privates['type_info.type_context_factory'] ??= new \Symfony\Component\TypeInfo\TypeContext\TypeContextFactory(NULL, [])));
    }
}
