<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_DoctrineEntityHydrationExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.doctrine_entity_hydration_extension' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Hydration\DoctrineEntityHydrationExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Hydration'.\DIRECTORY_SEPARATOR.'HydrationExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Hydration'.\DIRECTORY_SEPARATOR.'DoctrineEntityHydrationExtension.php';

        return $container->privates['ux.live_component.doctrine_entity_hydration_extension'] = new \Symfony\UX\LiveComponent\Hydration\DoctrineEntityHydrationExtension(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['doctrine'] ?? self::getDoctrineService($container));
        }, 1));
    }
}
