<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_Twig_CacheWarmerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.twig.cache_warmer' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Twig\TemplateCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'TemplateCacheWarmer.php';

        return $container->privates['ux.live_component.twig.cache_warmer'] = new \Symfony\UX\LiveComponent\Twig\TemplateCacheWarmer(($container->privates['twig.template_iterator'] ?? $container->load('getTwig_TemplateIteratorService')), 'live_components_twig_templates.map', $container->getParameter('container.build_hash'));
    }
}
