<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_LiveControllerAttributesCreatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.live_controller_attributes_creator' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Util\LiveControllerAttributesCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'LiveControllerAttributesCreator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'LiveResponder.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'TwigAttributeHelperFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'DeterministicTwigIdCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'FingerprintCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'TemplateMap.php';

        $a = ($container->privates['ux.live_component.component_hydrator'] ?? $container->load('getUx_LiveComponent_ComponentHydratorService'));

        if (isset($container->privates['ux.live_component.live_controller_attributes_creator'])) {
            return $container->privates['ux.live_component.live_controller_attributes_creator'];
        }

        $instance = new \Symfony\UX\LiveComponent\Util\LiveControllerAttributesCreator(($container->privates['ux.live_component.metadata_factory'] ?? $container->load('getUx_LiveComponent_MetadataFactoryService')), $a, ($container->privates['ux.live_component.attribute_helper_factory'] ??= new \Symfony\UX\LiveComponent\Util\TwigAttributeHelperFactory()), ($container->privates['ux.live_component.deterministic_id_calculator'] ??= new \Symfony\UX\LiveComponent\Twig\DeterministicTwigIdCalculator()), ($container->privates['ux.live_component.fingerprint_calculator'] ??= new \Symfony\UX\LiveComponent\Util\FingerprintCalculator($container->getEnv('APP_SECRET'))), ($container->services['router'] ?? self::getRouterService($container)), new \Symfony\UX\LiveComponent\LiveResponder(), ($container->privates['ux.live_component.twig.template_mapper'] ??= new \Symfony\UX\LiveComponent\Twig\TemplateMap(($container->targetDir.''.'/live_components_twig_templates.map'))));

        if (isset($container->privates['ux.live_component.live_controller_attributes_creator'])) {
            return $container->privates['ux.live_component.live_controller_attributes_creator'];
        }

        return $container->privates['ux.live_component.live_controller_attributes_creator'] = $instance;
    }
}
