<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerchangePasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zvHAzmR.App\Controller\UserController::changePassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.zvHAzmR.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.zvHAzmR": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\UserController::changePassword()', $container);

        if (isset($container->privates['.service_locator.zvHAzmR.App\\Controller\\UserController::changePassword()'])) {
            return $container->privates['.service_locator.zvHAzmR.App\\Controller\\UserController::changePassword()'];
        }

        return $container->privates['.service_locator.zvHAzmR.App\\Controller\\UserController::changePassword()'] = $instance;
    }
}
