<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_AddAttributesSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.add_attributes_subscriber' shared service.
     *
     * @return \Symfony\UX\LiveComponent\EventListener\AddLiveAttributesSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'AddLiveAttributesSubscriber.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-twig-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ComponentStack.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'TemplateMap.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['ux.live_component.add_attributes_subscriber'])) {
            return $container->privates['ux.live_component.add_attributes_subscriber'];
        }

        $instance = new \Symfony\UX\LiveComponent\EventListener\AddLiveAttributesSubscriber(($container->privates['ux.twig_component.component_stack'] ??= new \Symfony\UX\TwigComponent\ComponentStack()), ($container->privates['ux.live_component.twig.template_mapper'] ??= new \Symfony\UX\LiveComponent\Twig\TemplateMap(($container->targetDir.''.'/live_components_twig_templates.map'))), $a, (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Symfony\\UX\\LiveComponent\\Util\\LiveControllerAttributesCreator' => ['privates', 'ux.live_component.live_controller_attributes_creator', 'getUx_LiveComponent_LiveControllerAttributesCreatorService', true],
        ], [
            'Symfony\\UX\\LiveComponent\\Util\\LiveControllerAttributesCreator' => 'Symfony\\UX\\LiveComponent\\Util\\LiveControllerAttributesCreator',
        ]))->withContext('ux.live_component.add_attributes_subscriber', $container));

        if (isset($container->privates['ux.live_component.add_attributes_subscriber'])) {
            return $container->privates['ux.live_component.add_attributes_subscriber'];
        }

        return $container->privates['ux.live_component.add_attributes_subscriber'] = $instance;
    }
}
