<?php

namespace ContainerTDyK3k7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_MetadataFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.metadata_factory' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Metadata\LiveComponentMetadataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Metadata'.\DIRECTORY_SEPARATOR.'LiveComponentMetadataFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'type-info'.\DIRECTORY_SEPARATOR.'TypeResolver'.\DIRECTORY_SEPARATOR.'TypeResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'type-info'.\DIRECTORY_SEPARATOR.'TypeResolver'.\DIRECTORY_SEPARATOR.'TypeResolver.php';

        $a = ($container->privates['ux.twig_component.component_factory'] ?? $container->load('getUx_TwigComponent_ComponentFactoryService'));

        if (isset($container->privates['ux.live_component.metadata_factory'])) {
            return $container->privates['ux.live_component.metadata_factory'];
        }

        $instance = new \Symfony\UX\LiveComponent\Metadata\LiveComponentMetadataFactory($a, ($container->privates['property_info'] ?? self::getPropertyInfoService($container)), new \Symfony\Component\TypeInfo\TypeResolver\TypeResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ReflectionType' => ['privates', 'type_info.resolver.reflection_type', 'getTypeInfo_Resolver_ReflectionTypeService', true],
            'ReflectionParameter' => ['privates', 'type_info.resolver.reflection_parameter', 'getTypeInfo_Resolver_ReflectionParameterService', true],
            'ReflectionProperty' => ['privates', 'type_info.resolver.reflection_property', 'getTypeInfo_Resolver_ReflectionPropertyService', true],
            'ReflectionFunctionAbstract' => ['privates', 'type_info.resolver.reflection_return', 'getTypeInfo_Resolver_ReflectionReturnService', true],
        ], [
            'ReflectionType' => '?',
            'ReflectionParameter' => '?',
            'ReflectionProperty' => '?',
            'ReflectionFunctionAbstract' => '?',
        ])));

        if (isset($container->privates['ux.live_component.metadata_factory'])) {
            return $container->privates['ux.live_component.metadata_factory'];
        }

        return $container->privates['ux.live_component.metadata_factory'] = $instance;
    }
}
