<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTDyK3k7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTDyK3k7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTDyK3k7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTDyK3k7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTDyK3k7\App_KernelDevDebugContainer([
    'container.build_hash' => 'TDyK3k7',
    'container.build_id' => '2b2019b2',
    'container.build_time' => 1779076133,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTDyK3k7');
